
services:

  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database/data:/bar/lib/postgresql/data
    logging:
      driver: none

# docker run -d \
#         --name postgresql \
#         -e POSTGRES_PASSWORD=mysecretpassword \
#         -e PGDATA=/var/lib/postgresql/data/pgdata \
#         -v /home/connor/workspace/db/postgres:/var/lib/postgresql/data \
#         postgres






